### ISSUE TITLE
Security report

### ISSUE THREAD

**Issue by LukeTowers** [capture0x/WInterCms-SSTI#1]
Hello,

Was this issue reported via the security policy available here: https://github.com/wintercms/winter/security/policy? If it was it didn't make it to me, please let me know so that I can investigate and fix whatever issue would have prevented this from being reported to me and resolved before public release.

**Comment by capture0x** [comment]
Hello i send this issue cve and i tested winter cms 1.2.2 and winter cms
1.2.3 this issue working with 2 version , This versions have server side
template injection

6 Ara 2023 Çar, saat 22:20 tarihinde Luke Towers ***@***.***>
şunu yazdı:
